### ISSUE TITLE
enrichment pipeline

### ISSUE THREAD

**Issue by n3tsurge** [n3tsurge/elastic2hive#34]

**Comment by n3tsurge** [comment]
@SMAPPER  you can find sample plugins in the branch feature-enrichment-plugins.  One thing I still have yet to determine is how to handle the requirements for each plugin when using pipenv for managing pip

**Comment by n3tsurge** [comment]
also need to determine how we want to configure plugins...do we want to configure plugins in the global configuration file or have a configuration file in each plugin directory.

**Comment by SMAPPER** [comment]
We could take an approach similar to filebeat where they use /etc/filebeat/modules.d. The modules.d folder acts as a global folder for handling each module. So maybe for us we have a plugins.d folder and each plugin is set to disabled by default?

I like the idea of having either a single file to configure them all or a folder that contains all plugin configuration files. I lean towards the latter as it would be easier to script enable or modify things rather than going into each individual plugin's folder or trying to edit an ever growing plugin configuration file.

Thoughts?

**Comment by n3tsurge** [comment]
Makes sense...right now I have a plugins folder and each plugin is a subfolder of that with the plugin .py file and an optional config.toml.  when the plugins are imported it detects if it needs the config.toml or not and loads it automatically.

The plugins work in this method just fine, not sure how maintainable it is.

I like the idea of having a global setting for to enable each module so the master config.toml.would have a setting called plugins where you name the plugins you want enabled.

Brian Carroll

________________________________

**Comment by n3tsurge** [comment]
Plugin files are now located in the root of the `plugins` directory and config files (if required by the plugin) are in `plugin.conf`.  Python doesn't like naming the folder `plugins.d` because of the dot notation import methods that it uses, it would refer to them as `plugins.d.domainstats` and would look for a module named `d`

**Comment by n3tsurge** [comment]
Plugin Actions should fire on any observable that matches the Actions expected dataType
